import type { IBorderInfo } from "./global-interfaces";

interface IImageWithSizes {
	url: string;
	width: number;
	height: number;
};

export interface ICategory {
	id: number;
	orderBy: number;
	hdThumbnailUrl: string;
	thumbnailUrl: string;
	originalImageUrl: string;
	imageUrl: string;
	originalImage: IImageWithSizes;
	thumbnail: IImageWithSizes;
	borderInfo: IBorderInfo;
	name: string;
	nameTranslated: {
		ru: string;
	},
	url: string;
	autogeneratedSlug: string;
	customSlug?: string;
	productCount: number;
	description?: string;
	descriptionTranslated: {
		ru: string;
	},
	enabled: boolean;
	isSampleCategory: boolean;
	seoTitle: string;
	seoDescription?: string;
	alt: {
		main: string;
	}
};


export type CategoriesDTO = {
    total: number;
    count: number;
    offset: number;
    limit: number;
    items: ICategory[];
};



  